name: 🚀 Deploy

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  test:
    name: 🧪 Test
    runs-on: ubuntu-latest

    steps:
      - name: 👍 Checkout
        uses: actions/checkout@v4

      - name: 🧄 Use Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: 📥 Install dependencies
        run: bun install

      - name: 🧑‍🔬 Run tests
        run: bun test

  build-executables:
    name: 🔨 Build executables
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: 👍 Checkout
        uses: actions/checkout@v4

      - name: 🧄 Use Bun
        uses: oven-sh/setup-bun@v1

      - name: ⬇️ Clone Himnario API
        run: |
          git clone https://github.com/qhariN/himnario-adventista-api.git
          mv himnario-adventista-api himnario-adventista

      - name: 🔨 Build Himnario OBS
        run: |
          bun i --production
          VITE_SAME_HOST=true bun run build 
          cp -r dist/* himnario-adventista && rm -rf dist

      - name: ✍️ Write asset handlers
        run: bun scripts/write-asset-handlers.ts

      - name: 📥 Install dependencies
        run: cd himnario-adventista && bun i --production

      - name: 🔨 Build executables
        run: |
          cd himnario-adventista
          mkdir ../himnario-adventista-linux-x64
          bun build src/index.ts --compile --minify --sourcemap --outfile Himnario --target bun-linux-x64
          mv Himnario ../himnario-adventista-linux-x64
          mkdir ../himnario-adventista-macos-darwin-x64
          bun build src/index.ts --compile --minify --sourcemap --outfile Himnario --target bun-darwin-x64
          mv Himnario ../himnario-adventista-macos-darwin-x64
          mkdir ../himnario-adventista-macos-darwin-arm64
          bun build src/index.ts --compile --minify --sourcemap --outfile Himnario --target bun-darwin-arm64
          mv Himnario ../himnario-adventista-macos-darwin-arm64
          mkdir ../himnario-adventista-windows-x64
          bun build src/index.ts --compile --minify --sourcemap --outfile Himnario --target bun-windows-x64
          mv Himnario.exe ../himnario-adventista-windows-x64
          rm -rf node_modules

      - name: 🎵 Restore vocal files
        uses: actions/cache/restore@v4
        with:
          path: vocal
          key: vocal

      - name: 🎵 Restore instrumental files
        uses: actions/cache/restore@v4
        with:
          path: instrumental
          key: instrumental

      - name: 🛻 Move music files to build
        run: |
          mv vocal himnario-adventista/assets
          mv instrumental himnario-adventista/assets

      - name: 📦 Prepare linux-x64 zip
        run: |
          mv himnario-adventista-linux-x64/Himnario himnario-adventista
          rm -rf himnario-adventista-linux-x64
          zip -r himnario-linux-x64.zip himnario-adventista
          rm himnario-adventista/Himnario

      - name: 📦 Prepare macos-darwin-x64 zip
        run: |
          mv himnario-adventista-macos-darwin-x64/Himnario himnario-adventista
          rm -rf himnario-adventista-macos-darwin-x64
          zip -r himnario-macos-darwin-x64.zip himnario-adventista
          rm himnario-adventista/Himnario

      - name: 📦 Prepare macos-darwin-arm64 zip
        run: |
          mv himnario-adventista-macos-darwin-arm64/Himnario himnario-adventista
          rm -rf himnario-adventista-macos-darwin-arm64
          zip -r himnario-macos-darwin-arm64.zip himnario-adventista
          rm himnario-adventista/Himnario

      - name: 📦 Prepare windows-x64 zip
        run: |
          mv himnario-adventista-windows-x64/Himnario.exe himnario-adventista
          rm -rf himnario-adventista-windows-x64
          zip -r himnario-windows-x64.zip himnario-adventista
          rm himnario-adventista/Himnario.exe

      - name: 🗒️ Create release
        uses: softprops/action-gh-release@v2.0.8
        with:
          generate_release_notes: true
          files: |
            himnario-linux-x64.zip
            himnario-macos-darwin-x64.zip
            himnario-macos-darwin-arm64.zip
            himnario-windows-x64.zip
