name: 🚀 Deploy

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  test:
    name: 🧪 E2E Test
    runs-on: ubuntu-latest

    steps:
      - name: 👍 Checkout
        uses: actions/checkout@v4

      - name: 🧄 Use Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: 📥 Install dependencies
        run: bun install

      - name: 🧑‍🔬 Run tests
        run: bun test:e2e

  build-linux-executable:
    name: ⚒️ Build Linux executable
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: 👍 Checkout
        uses: actions/checkout@v4

      - name: 🧄 Use Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: 📥 Install dependencies
        run: bun install --production
  
      - name: ⚒️ Build project
        run: bun run build

      - name: ⚒️ Build executable
        run: cp scripts/serve.ts dist && cd dist && bun build serve.ts --compile --outfile Himnario

      - name: ⬆️ Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux-executable
          path: dist/Himnario
          if-no-files-found: error

  build-windows-executable:
    name: ⚒️ Build Windows executable
    runs-on: windows-latest
    needs: test

    steps:
      - name: 👍 Checkout
        uses: actions/checkout@v4

      - name: 🧄 Use Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: canary

      - name: 📥 Install dependencies
        run: bun install --production
  
      - name: ⚒️ Build project
        run: bun run build

      - name: ⚒️ Build executable
        run: cp scripts/serve.ts dist && cd dist && bun build serve.ts --compile --outfile Himnario.exe

      - name: ⬆️ Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-executable
          path: dist/Himnario.exe
          if-no-files-found: error

  create-release:
    name: 🚀 Create Release
    runs-on: ubuntu-latest
    needs: [build-linux-executable, build-windows-executable]

    steps:
      - name: ⬇️ Download artifacts
        uses: actions/download-artifact@v4

      - name: 🗒️ Create release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          files: |
            linux-executable/Himnario
            windows-executable/Himnario.exe