name: 🚀 Deploy

on:
  push:
    branches:
      - main

jobs:
  test:
    name: 🧪 E2E Test
    runs-on: ubuntu-latest

    steps:
      - name: 👍 Checkout
        uses: actions/checkout@v4

      - name: 🧄 Use Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: 📥 Install dependencies
        run: bun install

      - name: 🧑‍🔬 Run tests
        run: bun test:e2e

  build-linux-executable:
    name: 🔨 Build Linux executable
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: 👍 Checkout
        uses: actions/checkout@v4

      - name: 🧄 Use Bun
        uses: oven-sh/setup-bun@v1

      - name: Setup FFmpeg
        uses: AnimMouse/setup-ffmpeg@v1

      - name: 🔨 Build executable
        run: bun scripts/build-executable.ts

      - name: 💾 Save cantado files
        uses: actions/cache/save@v4
        with:
          path: cantado
          key: cantado

      - name: 💾 Save instrumental files
        uses: actions/cache/save@v4
        with:
          path: instrumental
          key: instrumental

      - name: ⬆️ Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: himnario-adventista-linux
          path: himnario-adventista
          if-no-files-found: error

  # build-macos-executable:
  #   name: 🔨 Build MacOS executable
  #   runs-on: macos-latest
  #   needs: test

  #   steps:
  #     - name: 👍 Checkout
  #       uses: actions/checkout@v4

  #     - name: 🧄 Use Bun
  #       uses: oven-sh/setup-bun@v1

  #     - name: 🔨 Build executable
  #       run: bun scripts/build-executable.ts

  #     - name: ⬆️ Upload artifact
  #       uses: actions/upload-artifact@v4
  #       with:
  #         name: himnario-adventista-macos
  #         path: himnario-adventista
  #         if-no-files-found: error

  # build-windows-executable:
  #   name: 🔨 Build Windows executable
  #   runs-on: windows-latest
  #   needs: test

  #   steps:
  #     - name: 👍 Checkout
  #       uses: actions/checkout@v4

  #     - name: 🧄 Use Bun
  #       uses: oven-sh/setup-bun@v1

  #     - name: 🔨 Build executable
  #       run: bun scripts/build-executable.ts

  #     - name: ⬆️ Upload artifact
  #       uses: actions/upload-artifact@v4
  #       with:
  #         name: himnario-adventista-windows
  #         path: himnario-adventista
  #         if-no-files-found: error

  create-release:
    name: 🚀 Create Release
    runs-on: ubuntu-latest
    needs: [build-linux-executable]

    steps:
      - name: ⬇️ Download artifacts
        uses: actions/download-artifact@v4

      - name: 🎵 Restore cantado files
        uses: actions/cache/restore@v4
        with:
          path: cantado
          key: cantado

      - name: 🎵 Restore instrumental files
        uses: actions/cache/restore@v4
        with:
          path: instrumental
          key: instrumental

      - name: 📦 Prepare Linux executable
        run: |
          cp -r cantado himnario-adventista-linux/assets
          cp -r instrumental himnario-adventista-linux/assets
          zip -r himnario-linux.zip himnario-adventista-linux
          rm -rf himnario-adventista-linux

      - name: 📦 Prepare MacOS executable
        run: |
          cp -r cantado himnario-adventista-macos/assets
          cp -r instrumental himnario-adventista-macos/assets
          zip -r himnario-macos.zip himnario-adventista-macos
          rm -rf himnario-adventista-macos

      - name: 📦 Prepare Windows executable
        run: |
          cp -r cantado himnario-adventista-windows/assets
          cp -r instrumental himnario-adventista-windows/assets
          zip -r himnario-windows.zip himnario-adventista-windows
          rm -rf himnario-adventista-windows

      - name: 🗒️ Create release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          files: |
            himnario-linux.zip
            himnario-macos.zip
            himnario-windows.zip