name: 🚀 Deploy

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  test:
    name: 🧪 E2E Test
    runs-on: ubuntu-latest

    steps:
      - name: 👍 Checkout
        uses: actions/checkout@v4

      - name: 🧄 Use Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: 📥 Install dependencies
        run: bun install

      - name: 🧑‍🔬 Run tests
        run: bun test:e2e

  build-linux-executable:
    name: 🔨 Build Linux executable
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: 👍 Checkout
        uses: actions/checkout@v4

      - name: 🧄 Use Bun
        uses: oven-sh/setup-bun@v1

      - name: 🔨 Build executable
        run: bun scripts/build-executable.ts

      - name: ⬆️ Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: himnario-adventista-linux
          path: himnario-adventista
          if-no-files-found: error

  build-macos-executable:
    name: 🔨 Build MacOS executable
    runs-on: macos-latest
    needs: test

    steps:
      - name: 👍 Checkout
        uses: actions/checkout@v4

      - name: 🧄 Use Bun
        uses: oven-sh/setup-bun@v1

      - name: 🔨 Build executable
        run: bun scripts/build-executable.ts

      - name: ⬆️ Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: himnario-adventista-macos
          path: himnario-adventista
          if-no-files-found: error

  build-windows-executable:
    name: 🔨 Build Windows executable
    runs-on: windows-latest
    needs: test

    steps:
      - name: 👍 Checkout
        uses: actions/checkout@v4

      - name: 🧄 Use Bun
        uses: oven-sh/setup-bun@v1

      - name: 🔨 Build executable
        run: bun scripts/build-executable.ts

      - name: ⬆️ Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: himnario-adventista-windows
          path: himnario-adventista
          if-no-files-found: error

  create-release:
    name: 🚀 Create Release
    runs-on: ubuntu-latest
    needs: [build-linux-executable, build-macos-executable, build-windows-executable]

    steps:
      - name: ⬇️ Download artifacts
        uses: actions/download-artifact@v4

      - name: ⬇️ Restore music files
        uses: actions/cache/restore@v4
        with:
          path: hymns
          key: music-files

      - name: 📩 Copy music folder to Linux executable
        run: |
          mkdir -p himnario-adventista-linux/assets
          cp -r hymns himnario-adventista-linux/assets

      - name: 📩 Copy music folder to macOS executable
        run: |
          mkdir -p himnario-adventista-macos/assets
          cp -r hymns himnario-adventista-macos/assets

      - name: 📩 Copy music folder to Windows executable
        run: |
          mkdir -p himnario-adventista-windows/assets
          cp -r hymns himnario-adventista-windows/assets

      - name: 📦 Zip executables
        run: |
          zip -r himnario-linux.zip himnario-adventista-linux
          zip -r himnario-macos.zip himnario-adventista-macos
          zip -r himnario-windows.zip himnario-adventista-windows

      - name: 🗒️ Create release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          files: |
            himnario-linux.zip
            himnario-macos.zip
            himnario-windows.zip