name: 🧪 Testing

on: push

jobs:
  test:
    name: 🧪 E2E Test
    runs-on: ubuntu-latest

    steps:
      - name: 👍 Checkout
        uses: actions/checkout@v4

      - name: 🧄 Use Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: 📥 Install dependencies
        run: bun install

      - name: 🧑‍🔬 Run tests
        run: bun test:e2e